
#define   NHEP_LAYER    ( 1<<CED_LAYER_SHIFT)
#define   CHEP_LAYER    (11<<CED_LAYER_SHIFT)

#define TPC_TR_N_LAYER  ( 2<<CED_LAYER_SHIFT)
#define TPC_TR_C_LAYER (12<<CED_LAYER_SHIFT)

#define     TPC_LAYER   ( 3<<CED_LAYER_SHIFT)
#define   TPC_E_LAYER   (13<<CED_LAYER_SHIFT)

#define  ECAL_COL_LAYER ( 4<<CED_LAYER_SHIFT)
#define  HCAL_COL_LAYER (14<<CED_LAYER_SHIFT)

#define    ECAL_LAYER   ( 5<<CED_LAYER_SHIFT)
#define    HCAL_LAYER   (15<<CED_LAYER_SHIFT)

#define     RED_S_LAYER ( 6<<CED_LAYER_SHIFT)
#define   RED_SE_LAYER  (16<<CED_LAYER_SHIFT)

#define     RED_LAYER   ( 7<<CED_LAYER_SHIFT)
#define   RED_E_LAYER   (17<<CED_LAYER_SHIFT)

#define   GREEN_LAYER   ( 8<<CED_LAYER_SHIFT)
#define GREEN_E_LAYER   (18<<CED_LAYER_SHIFT)

#define    BLUE_LAYER   ( 9<<CED_LAYER_SHIFT)
#define  BLUE_E_LAYER   (19<<CED_LAYER_SHIFT)

#define ECAL_ALL_LAYER  ( 0<<CED_LAYER_SHIFT)
#define HCAL_ALL_LAYER  (10<<CED_LAYER_SHIFT)
